// Flat ESLint config for the whole workspace: one file at the root, matching
// how check:docs / check:design / check:scripts are single root-level gates.
// Runs as `pnpm run check:lint`, inside the full `pnpm run check`.
//
// SCOPE NOTE: .astro files are deliberately NOT linted here. The entire Astro
// ESLint toolchain (eslint-plugin-astro and astro-eslint-parser, every current
// version) declares `engines.node: ^22.22.3 || ^24.16.0 || >=26.3.0`, and this
// repo pins Node 22.19 in .nvmrc, which CI reads. Installing it would break the
// pinned runtime rather than lint anything. Astro files are still typechecked
// by `astro check` in check:web (92 files, 0 errors). To close the gap, bump
// .nvmrc + engines.node to a Node 22 LTS >= 22.22.3, then add
// eslint-plugin-astro and an `**/*.astro` block using astro.configs.recommended.
//
// Blocks below, in order:
//   1. ignores       build output plus anything a generator owns
//   2. base          eslint:recommended
//   3. .mjs          plain Node scripts (scripts/, apps/web/scripts/)
//   4. .ts/.tsx      typescript-eslint recommended, NOT type-aware
//   5. typed overlay the promise rules, only where a tsconfig.json includes it
//   6. apps/cms tsx  React hooks
//   7. seeds/tests   targeted relaxations plus vitest rules
//   8. prettier      last, so formatting rules lose to prettier
import js from "@eslint/js";
import vitest from "@vitest/eslint-plugin";
import prettier from "eslint-config-prettier/flat";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * Files where `projectService` can resolve a tsconfig.json that ACTUALLY
 * includes them. projectService walks up for the nearest file named exactly
 * `tsconfig.json` and errors when that config excludes the file, so this list
 * mirrors the include/exclude of apps/web/{tsconfig,worker/tsconfig,
 * test/tsconfig}.json and apps/cms/tsconfig.json. Widening it without widening
 * a tsconfig produces "was not found by the project service".
 */
const TYPED = [
  "apps/cms/**/*.{ts,tsx}",
  "apps/web/src/**/*.ts",
  "apps/web/worker/index.ts",
  "apps/web/test/**/*.test.ts",
];

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/",
      "**/dist/",
      "**/.astro/",
      "**/.next/",
      "**/.vercel/",
      "**/.wrangler/",
      // Generated by tooling; same list as .prettierignore. Linting these
      // fights the generator on its next run.
      "apps/cms/src/payload-types.ts",
      "apps/cms/src/migrations/",
      "**/importMap.js",
      "apps/web/worker-configuration.d.ts",
      "apps/web/src/env.d.ts",
      // Transfer artifacts and DB dumps, never source.
      "scripts/content-packages/",
      "scripts/backups/",
      // Chrome-for-Testing install (ensure-chrome); not our source.
      ".browsers/",
    ],
  },

  {
    files: ["**/*.{js,mjs,cjs,ts,tsx}"],
    extends: [js.configs.recommended],
    languageOptions: { ecmaVersion: 2024, sourceType: "module" },
    linterOptions: { reportUnusedDisableDirectives: "error" },
  },

  {
    files: ["**/*.mjs", "**/*.cjs", "**/*.js"],
    languageOptions: { globals: globals.nodeBuiltin },
    rules: {
      "no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },

  // Neither app sets noUnusedLocals, so tsc does not catch unused bindings.
  {
    files: ["**/*.{ts,tsx}"],
    extends: [tseslint.configs.recommended],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
      // apps/web gets this free from verbatimModuleSyntax (astro's strict
      // preset); this extends the same discipline to apps/cms so a type-only
      // import can never pull a module into the bundle.
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "separate-type-imports" },
      ],
      // A suppression has to say what it suppresses.
      "@typescript-eslint/ban-ts-comment": [
        "error",
        { "ts-expect-error": "allow-with-description" },
      ],
      eqeqeq: ["error", "smart"],
    },
  },

  // Type-aware overlay: four rules, all "this is a bug", none stylistic.
  // Deliberately NOT recommendedTypeChecked -- its no-unsafe-* family fires on
  // every Payload `data` / `originalDoc` / `req` boundary, which would be
  // hundreds of findings against code that is correct.
  {
    files: TYPED,
    // Node-vitest files live in test/tsconfig.node.json (not tsconfig.json),
    // so projectService cannot type-check them via the nearest tsconfig.json.
    ignores: [
      "apps/web/test/content.test.ts",
      "apps/web/test/media-filename.test.ts",
      "apps/web/test/media-match.test.ts",
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/no-array-delete": "error",
    },
  },

  // content.test.ts is the one .ts file no tsconfig.json includes: it lives in
  // test/tsconfig.node.json, and projectService only recognizes that exact
  // filename. Typed rules are off for it explicitly, so the reason stays
  // visible rather than being hidden behind allowDefaultProject.
  {
    files: ["apps/web/test/content.test.ts"],
    extends: [tseslint.configs.disableTypeChecked],
  },

  // Payload admin React components. Only the two classic rules: v7's
  // `recommended` also enables the React Compiler set, whose
  // set-state-in-effect flags publish-history.tsx, which is correct code.
  {
    files: ["apps/cms/src/**/*.tsx"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "error",
    },
  },

  // Seeds build obviously-fake fixture data against Payload's loose block and
  // richtext shapes; typing those out adds no safety.
  {
    files: ["apps/cms/seed/**/*.ts"],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },

  // A curated four, not the recommended set: this codebase is heavily
  // commented on purpose, so vitest/no-commented-out-tests would be a
  // false-positive generator.
  {
    files: ["apps/*/test/**/*.test.ts"],
    plugins: { vitest },
    rules: {
      "vitest/no-focused-tests": "error",
      "vitest/no-disabled-tests": "error",
      "vitest/expect-expect": "error",
      "vitest/valid-expect": "error",
    },
  },

  prettier,
);
