/**
 * Cookieless analytics CONFIG (ADR-0003) -- pure (no posthog-js runtime
 * import) so it is unit-testable. `boot.ts` performs the actual
 * `posthog.init(KEY, POSTHOG_OPTIONS)` side effect in the browser.
 * See docs/dev/analytics.md for the full posture and the project-settings
 * toggles that pair with these client options.
 */
import type { CaptureResult, PostHogConfig } from "posthog-js";

export const KEY: string | undefined = import.meta.env.PUBLIC_POSTHOG_KEY;

// Ingestion goes through the site's own Worker route /qm/* (first party, so
// blocklists that know PostHog's domains do not apply; see worker/index.ts).
// PUBLIC_POSTHOG_HOST can override, e.g. to hit eu.i.posthog.com directly
// while debugging the proxy. A root-relative api_host is the documented
// same-origin pattern and only ever resolves on the allowlisted prod hosts.
export const HOST: string = import.meta.env.PUBLIC_POSTHOG_HOST || "/qm";
// The app UI stays on PostHog's real domain so links generated by the SDK
// (toolbar, error tracking) point at the EU app, not at our proxy path.
const UI_HOST = "https://eu.posthog.com";

/**
 * FAIL-SAFE APEX ALLOWLIST: only the real production hostnames collect.
 * Everything else -- localhost (`make dev` / `make preview`), 127.0.0.1, LAN
 * IPs, `*.workers.dev`, the VRT container, CI -- is excluded, so no build can
 * ever pollute the production project even with PUBLIC_POSTHOG_KEY set.
 * (Allowlist, not a denylist: an unknown host defaults to NOT collecting,
 * which is the safe direction.)
 */
const PROD_HOSTS = new Set(["q-summit.com", "www.q-summit.com"]);
export function shouldCollect(hostname: string | undefined): boolean {
  return !!hostname && PROD_HOSTS.has(hostname);
}

/**
 * Browser fetch-layer failures, anchored to the exact per-engine message:
 * Safari "Load failed", Chrome "Failed to fetch", Firefox "NetworkError...",
 * plus common iOS transport aborts. These are unhandled rejections from
 * requests dying on flaky or content-blocked mobile networks -- no stack, not
 * actionable. With `capture_exceptions` on, the SDK otherwise recaptures its
 * OWN failed beacons as this noise (an observed iOS-Safari-only
 * `TypeError: Load failed` loop).
 */
export const EXCEPTION_NETWORK_NOISE =
  /^(Load failed|Failed to fetch|NetworkError when attempting to fetch resource|The network connection was lost\.|The request timed out\.|cancelled|canceled)$/;

/** Client-side payload gate -- drops unactionable network-failure exceptions before they leave the browser. */
export function beforeSend(
  payload: CaptureResult | null,
): CaptureResult | null {
  if (!payload) return payload;
  if (payload.event === "$exception") {
    const props = payload.properties ?? {};
    const list = props.$exception_list as Array<{ value?: string }> | undefined;
    const values = props.$exception_values as string[] | undefined;
    const value = (list?.[0]?.value ?? values?.[0])?.trim();
    if (value && EXCEPTION_NETWORK_NOISE.test(value)) return null;
  }
  return payload;
}

/**
 * COOKIELESS config (ADR-0003). `persistence: 'memory'` + `cookieless_mode:
 * 'always'` write nothing to the device (no ePrivacy Art. 5(3) trigger, no
 * consent banner); identity is a transient server-side daily-salt hash, so
 * within-day sessions hold together without any client identifier.
 * Collects: `$pageview`, `$pageleave` (bounce/duration), `$web_vitals`,
 * heatmap coordinates, `$exception` (error tracking), and the taxonomy in
 * `events.ts`. NO autocapture event spam (heatmaps give click coverage
 * without per-element events), NO session replay, NO surveys.
 */
export const POSTHOG_OPTIONS = {
  api_host: HOST,
  ui_host: UI_HOST,
  // Pin the SDK's dated default tier (newest posthog-js 1.407.3 ships) so an SDK
  // bump can never silently change behavior. Every dated behavior we do not set
  // below is already inert for us: autocapture:false kills rageclick capture,
  // disable_session_recording:true kills the replay tiers, persistence:'memory'
  // makes the localStorage debounce/split-storage tiers moot, and boot.ts never
  // init()s on localhost so the internal-test-hostname tier never fires. Bump
  // this date deliberately (re-audit, then upgrade the SDK), never by accident.
  defaults: "2026-06-25",
  autocapture: false, // no per-element click events; the heatmap stream covers click coverage
  capture_pageview: true, // MPA full-page loads -> one auto pageview per load is correct
  capture_pageleave: true, // accurate bounce rate + session duration (also feeds scrollmaps)
  capture_exceptions: true, // error tracking: unhandled errors + rejections (noise-gated in beforeSend)
  capture_performance: { web_vitals: true }, // explicit so web vitals never silently ride a remote toggle
  capture_heatmaps: true, // coordinate-stream heatmaps are cookieless-safe (no element text, no PII)
  person_profiles: "never", // ADR-0003 anonymous events only; identify() must never be called
  persistence: "memory", // no cookie, no localStorage -> no Art. 5(3) storage trigger
  cookieless_mode: "always", // server-side daily-salt hash; requires the project-settings toggle
  disable_session_recording: true, // replay is incompatible with the cookieless posture -- keep off
  disable_surveys: true, // no survey popups on a marketing site
  before_send: beforeSend,
} satisfies Partial<PostHogConfig>;
