/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    partners: Partner;
    jobs: Job;
    speakers: Speaker;
    team: Team;
    'past-teams': PastTeam;
    faqs: Faq;
    testimonials: Testimonial;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    partners: PartnersSelect<false> | PartnersSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'past-teams': PastTeamsSelect<false> | PastTeamsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'page-home': PageHome;
    'page-whyq': PageWhyq;
    'page-speaker': PageSpeaker;
    'page-partner': PagePartner;
    'page-program': PageProgram;
    'page-hackathon': PageHackathon;
    'page-our-team': PageOurTeam;
    'page-jobs': PageJob;
    'page-tickets': PageTicket;
    'page-contact': PageContact;
    'page-past-teams': PagePastTeam;
    'site-settings': SiteSetting;
    legal: Legal;
  };
  globalsSelect: {
    'page-home': PageHomeSelect<false> | PageHomeSelect<true>;
    'page-whyq': PageWhyqSelect<false> | PageWhyqSelect<true>;
    'page-speaker': PageSpeakerSelect<false> | PageSpeakerSelect<true>;
    'page-partner': PagePartnerSelect<false> | PagePartnerSelect<true>;
    'page-program': PageProgramSelect<false> | PageProgramSelect<true>;
    'page-hackathon': PageHackathonSelect<false> | PageHackathonSelect<true>;
    'page-our-team': PageOurTeamSelect<false> | PageOurTeamSelect<true>;
    'page-jobs': PageJobsSelect<false> | PageJobsSelect<true>;
    'page-tickets': PageTicketsSelect<false> | PageTicketsSelect<true>;
    'page-contact': PageContactSelect<false> | PageContactSelect<true>;
    'page-past-teams': PagePastTeamsSelect<false> | PagePastTeamsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Partner companies and logos (used on / and /partner/). Owned by Partner. Page chrome for /partner/ is under Website pages → Partners.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * The company name exactly as it should read on the site. Two partners cannot share a name.
   */
  name: string;
  /**
   * Full address including https://. Use "#" if the partner has no website.
   */
  websiteUrl: string;
  /**
   * Company logo. Prefer SVG, otherwise a PNG or WebP with a transparent background.
   */
  logo: number | Media;
  /**
   * Sponsorship level. Platinum logos are the largest and sit at the top of /partner/; Media logos are the smallest and sit last.
   */
  tier:
    | 'platinum'
    | 'gold'
    | 'silver'
    | 'starter'
    | 'knowledge'
    | 'event'
    | 'mobility'
    | 'university-and-network'
    | 'media';
  /**
   * Sort position within its tier, ascending. Lower numbers appear higher. Decimals are allowed (7.5 slots between 7 and 8), so inserting never means renumbering. New entries land after the current last one.
   */
  order?: number | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images used across the site (logos, photos, portraits). Upload sharp originals up to 5 MB; the site generates small sizes itself. Open a file to see everywhere it is used before you change or delete it. The hero and hackathon background videos are not here: they are too large for this library and IT replaces them directly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers and for search. Describe the content, not the file.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Job board postings on /job-listings/. Owned by Partner. Slug is the public URL, do not change it on existing postings. Page chrome is under Website pages → Jobs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  company: string;
  /**
   * Free text, e.g. "Munich (hybrid)".
   */
  location?: string | null;
  workload?: ('full-time' | 'internship' | 'working-student') | null;
  /**
   * The posting body. Headings, lists and links; images belong in the Logo field on the next tab.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Where the Apply button goes: a link, or a mailto: address if the partner takes applications by email.
   */
  applyUrl: string;
  /**
   * Company logo shown on the job card.
   */
  logo: number | Media;
  /**
   * The web address of this posting (q-summit.com/jobs/<slug>). Leave it alone on a posting that is already live, or published links break.
   */
  slug: string;
  /**
   * Sort position, ascending. Lower numbers appear higher. Decimals are allowed (7.5 slots between 7 and 8), so inserting never means renumbering. New entries land after the current last one.
   */
  order?: number | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Speakers and moderators (used on / and /speaker/). Owned by PR. Page chrome for /speaker/ is under Website pages → Speakers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  /**
   * Optional. Leave empty until a real photo is available; the card renders without one.
   */
  photo?: (number | null) | Media;
  /**
   * Job title or role.
   */
  role: string;
  /**
   * Leave empty if none applies.
   */
  company?: string | null;
  /**
   * Leave empty and the card shows "Role, Company" from the two fields above. Fill this in only when the card needs different wording.
   */
  roleLine?: string | null;
  /**
   * Short bio paragraph, shown on the homepage main-stage card.
   */
  bio?: string | null;
  /**
   * Where the speaker appears on the site.
   */
  group: 'current' | 'moderation' | 'panel' | 'previous';
  /**
   * Conference edition year, e.g. 2026. Required for current-edition entries; optional for highlights when the edition is unknown.
   */
  year?: number | null;
  /**
   * Sort position within its group, ascending. Lower numbers appear higher. Decimals are allowed (7.5 slots between 7 and 8), so inserting never means renumbering. New entries land after the current last one.
   */
  order?: number | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Current board and team members ( /our-team/ ). Owned by Chair + PR. When a board retires, add its group photo under Past Teams. Page headings are under Website pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * Position title.
   */
  role: string;
  /**
   * Portrait shown on /our-team/.
   */
  photo: number | Media;
  /**
   * Full profile address. Shown as a LinkedIn icon on the member's card; leave empty to show no icon.
   */
  linkedin?: string | null;
  /**
   * Which section this person appears under on /our-team/. The site spells the short names out, so "pr" shows as "Public Relations".
   */
  division: 'chair' | 'pr' | 'partner' | 'finance' | 'operations' | 'concept' | 'it';
  /**
   * Board year in "YY/YY" format, e.g. 26/27.
   */
  year: string;
  /**
   * Sort position within its division, ascending. Lower numbers appear higher. Decimals are allowed (7.5 slots between 7 and 8), so inserting never means renumbering. New entries land after the current last one.
   */
  order?: number | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One group photo per past board year ( /past-teams/ ). Owned by Chair + PR. Add a year when a board retires; never overwrite or delete a past year. Current members live under Team; page headings are under Website pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-teams".
 */
export interface PastTeam {
  id: number;
  /**
   * Board year in "YY/YY" format, e.g. 25/26. One entry per year.
   */
  year: string;
  /**
   * Group photo of that year's team.
   */
  photo: number | Media;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * FAQ Q&As shown on Home, Program, and Hackathon. Owned by Concept + PR. Pick the Page field so each question lands on the right accordion.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Which page's FAQ section this entry appears in.
   */
  page: 'home' | 'program' | 'hackathon';
  /**
   * Sort position within the page's FAQ list, ascending. Lower numbers appear higher. Decimals are allowed (7.5 slots between 7 and 8), so inserting never means renumbering. New entries land after the current last one.
   */
  order: number;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Quotes on the partners page (/partner/). Owned by Partner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  /**
   * Person and company, e.g. Jane Doe, Example GmbH. Each quote needs a different one.
   */
  attribution: string;
  /**
   * Optional small portrait shown next to the quote.
   */
  photo?: (number | null) | Media;
  /**
   * Sort position, ascending. Lower numbers appear higher. Decimals are allowed (7.5 slots between 7 and 8), so inserting never means renumbering. New entries land after the current last one.
   */
  order?: number | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * CMS accounts. Roles and divisions normally come from Google Workspace groups on login; prefer changing group membership over editing users here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Divisions whose content this account may edit.
   */
  divisions?: ('chair' | 'pr' | 'partner' | 'finance' | 'operations' | 'concept' | 'it')[] | null;
  /**
   * Editors propose drafts only. Heads review and publish. Admins manage users and Legal.
   */
  roles: ('editor' | 'approver' | 'admin')[];
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'past-teams';
        value: number | PastTeam;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  websiteUrl?: T;
  logo?: T;
  tier?: T;
  order?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  location?: T;
  workload?: T;
  description?: T;
  applyUrl?: T;
  logo?: T;
  slug?: T;
  order?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  role?: T;
  company?: T;
  roleLine?: T;
  bio?: T;
  group?: T;
  year?: T;
  order?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  linkedin?: T;
  division?: T;
  year?: T;
  order?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "past-teams_select".
 */
export interface PastTeamsSelect<T extends boolean = true> {
  year?: T;
  photo?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  page?: T;
  order?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  photo?: T;
  order?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  divisions?: T;
  roles?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Copy for / on the live site. Owned by PR + Concept. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home".
 */
export interface PageHome {
  id: number;
  hero: {
    headline: string;
    tagline: string;
    /**
     * Rotating banner lines (e.g. thank-you message, next date). Each row is one line.
     */
    announcementLines?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Hero call-to-action, e.g. {label: "Learn more", href: "#why-attend"}.
     */
    cta: {
      label: string;
      /**
       * A full URL (https://...), a mailto: address, an internal path (e.g. "/whyq"), or an in-page anchor (e.g. "#why-attend").
       */
      href: string;
    };
  };
  event: {
    /**
     * First day of the conference.
     */
    startDate: string;
    /**
     * Last day of the conference. Same as the start date for a one-day event.
     */
    endDate: string;
  };
  stats: {
    heading: string;
    intro: string;
    /**
     * Headline numbers, e.g. 1500 Participants.
     */
    items?:
      | {
          value: string;
          label: string;
          /**
           * Partner/company names shown in the logo band (index page only).
           */
          logos?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  partnerBand: {
    /**
     * One entry per logo group (Startup/Corporate, Network, ...).
     */
    items?:
      | {
          value: string;
          label: string;
          /**
           * Partner/company names shown in the logo band (index page only).
           */
          logos?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      /**
       * A full URL (https://...), a mailto: address, an internal path (e.g. "/whyq"), or an in-page anchor (e.g. "#why-attend").
       */
      href: string;
    };
  };
  previousSpeakers: {
    heading: string;
    intro: string;
    cta: {
      label: string;
      /**
       * A full URL (https://...), a mailto: address, an internal path (e.g. "/whyq"), or an in-page anchor (e.g. "#why-attend").
       */
      href: string;
    };
  };
  whyAttend: {
    heading: string;
    intro: string;
    /**
     * One card per reason to attend.
     */
    cards?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      /**
       * A full URL (https://...), a mailto: address, an internal path (e.g. "/whyq"), or an in-page anchor (e.g. "#why-attend").
       */
      href: string;
    };
  };
  faqSection: {
    heading: string;
    intro: string;
    cta: {
      label: string;
      /**
       * A full URL (https://...), a mailto: address, an internal path (e.g. "/whyq"), or an in-page anchor (e.g. "#why-attend").
       */
      href: string;
    };
  };
  /**
   * Browser tab and social-share title for the home page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /whyq/ on the live site. Owned by PR + Concept. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-whyq".
 */
export interface PageWhyq {
  id: number;
  heading: string;
  intro: string;
  /**
   * One section per audience (attendees, startups, investors, partners, founders), in display order.
   */
  audiences: {
    /**
     * Anchor id, e.g. "attendees". Keep stable; other pages may link to it.
     */
    anchorId: string;
    heading: string;
    intro: string;
    /**
     * Optional highlight bullets (title + description) beside the photo.
     */
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Section photo.
     */
    imageFile: number | Media;
    /**
     * Alt text for the section photo (kept separate from the media library's own alt).
     */
    imageAlt: string;
    /**
     * Show the photo on the left (checked) or right (unchecked) of its text.
     */
    imageLeft?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Browser tab and social-share title for the whyq page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /speaker/ on the live site. Owned by PR + Concept. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-speaker".
 */
export interface PageSpeaker {
  id: number;
  heading: string;
  intro: string;
  /**
   * Main-stage panel topic cards.
   */
  panels: {
    title: string;
    description: string;
    /**
     * Icon shown on the card. Ask IT to register a new icon in speaker.astro's PANEL_ICONS before it can appear here.
     */
    iconKey: 'globe' | 'refund' | 'ai';
    id?: string | null;
  }[];
  /**
   * Browser tab and social-share title for the speaker page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /partner/ on the live site. Owned by Partner. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-partner".
 */
export interface PagePartner {
  id: number;
  heading: string;
  cta: {
    heading: string;
    text: string;
    buttonLabel: string;
    /**
     * http(s) URL or mailto: address.
     */
    buttonHref: string;
  };
  /**
   * Browser tab and social-share title for the partner page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /program/ on the live site. Owned by PR + Concept. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-program".
 */
export interface PageProgram {
  id: number;
  agenda: {
    heading: string;
    intro: string;
    /**
     * One row per agenda item (Speeches, Workshops, ...).
     */
    items?:
      | {
          date: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  faqSection: {
    heading: string;
    intro: string;
  };
  closingCta: {
    heading: string;
    text: string;
  };
  /**
   * Browser tab and social-share title for the program page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /hackathon/ on the live site. Owned by PR + Concept. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-hackathon".
 */
export interface PageHackathon {
  id: number;
  hero: {
    headline: string;
    tagline: string;
    cta: {
      label: string;
      /**
       * A full URL (https://...), a mailto: address, an internal path (e.g. "/whyq"), or an in-page anchor (e.g. "#why-attend").
       */
      href: string;
    };
  };
  partners: {
    heading: string;
    groups: {
      /**
       * Section heading, e.g. Challenge Partners.
       */
      group: string;
      partners: {
        name: string;
        href: string;
        /**
         * Logo asset registered in code (HackPartners.astro's logoAssets), not an uploaded file. Ask IT to register a new logo before it can appear in this list.
         */
        logoFile:
          | '69bfc230ceecbebceff708fc_new-logo.webp'
          | '69b17a0e089f34c65a5e14a2_Picnic_logo.svg'
          | '69bfc037724d038aa2ba26bc_image.png'
          | '69c25665fc7b9cf5fb7a2889_f6961aac836f-Logo__2_.webp'
          | '69d00444ac69243eaf2b4f4f_istari-logo.svg'
          | '69c255cf7613b98e497cf289_OpenAI-black-wordmark(1).webp'
          | '69b2e8289e0d3b7dd0ae9529_lovable_logo.svg'
          | '69c99a0acf960a512107bc95_Anthropic_logo.svg'
          | '69c256c8d3ff156cf6877066_elevenlabs-logo-black.webp'
          | '69ccf786df18a395b3fee7fd_n8n_pink%2Bblack_logo.svg'
          | '69d40a60aa0c813fdc6344eb_featherlessai-transparent.webp'
          | '69d675fef0b853cb5df97e4e_liveavatar_logo_vertical_dark.webp'
          | '69b458c74be9d2023714bcbf_itmx_logo.webp'
          | '69d00453416ddd4a45dad964_mlh-logo-color-dark.svg';
        /**
         * Optional footnote, e.g. "Challenge to be announced".
         */
        note?: string | null;
        id?: string | null;
      }[];
      id?: string | null;
    }[];
  };
  benefits: {
    heading: string;
    /**
     * Why Q-Hackathon cards (Prizes, Networking, ...).
     */
    cards?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  schedule: {
    heading: string;
    intro: string;
    items?:
      | {
          date: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  faqSection: {
    heading: string;
    intro: string;
  };
  closingCta: {
    heading: string;
    text: string;
    mailtoLabel: string;
    mailtoEmail: string;
  };
  /**
   * Browser tab and social-share title for the hackathon page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /our-team/ on the live site. Owned by PR + Concept. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-our-team".
 */
export interface PageOurTeam {
  id: number;
  heading: string;
  /**
   * Browser tab and social-share title for the our team page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /job-listings/ on the live site. Owned by Partner. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-jobs".
 */
export interface PageJob {
  id: number;
  heading: string;
  intro: string;
  /**
   * Heading above the apply link on each job's detail view, e.g. "How to get in touch:".
   */
  detailHowToContactHeading: string;
  /**
   * Browser tab and social-share title for the job listings page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /ticket-categories/ on the live site. Owned by PR + Concept. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-tickets".
 */
export interface PageTicket {
  id: number;
  tiers: {
    heading: string;
    intro: string;
    items: {
      name: string;
      /**
       * e.g. "74€".
       */
      price: string;
      features: {
        text: string;
        id?: string | null;
      }[];
      /**
       * Optional footnote, e.g. "Student ID required".
       */
      note?: string | null;
      buyLabel: string;
      /**
       * Ticket purchase link, e.g. the Vivenu checkout URL.
       */
      buyHref: string;
      id?: string | null;
    }[];
  };
  comparison: {
    heading: string;
    intro: string;
    /**
     * Table column headers, in display order.
     */
    tiers: {
      name: string;
      price: string;
      audience: string;
      id?: string | null;
    }[];
    groups: {
      /**
       * Section heading in the table.
       */
      group: string;
      rows: {
        feature: string;
        /**
         * One row per comparison tier, in the same order as comparison.tiers above. Check = included.
         */
        included: {
          value?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[];
      id?: string | null;
    }[];
    /**
     * Footnote below the table, e.g. On-Conference variations.
     */
    academicNote: string;
  };
  categories: {
    heading: string;
    items: {
      /**
       * e.g. "Student Ticket: 74€".
       */
      label: string;
      bullets: {
        text: string;
        id?: string | null;
      }[];
      id?: string | null;
    }[];
  };
  /**
   * Browser tab and social-share title for the ticket categories page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /contact/ on the live site. Owned by PR + Concept. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact".
 */
export interface PageContact {
  id: number;
  board: {
    heading: string;
    paragraphs: {
      text: string;
      id?: string | null;
    }[];
    members: {
      name: string;
      role: string;
      email: string;
      /**
       * e.g. "Send E-Mail".
       */
      linkLabel: string;
      id?: string | null;
    }[];
  };
  reachOut: {
    heading: string;
    paragraphs: {
      text: string;
      id?: string | null;
    }[];
    items: {
      label: string;
      /**
       * Optional; leave empty for a postal-address-only entry.
       */
      email?: string | null;
      details: {
        text: string;
        id?: string | null;
      }[];
      id?: string | null;
    }[];
  };
  /**
   * Browser tab and social-share title for the contact page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for /past-teams/ on the live site. Owned by PR + Concept. Use Live Preview (eye icon) to see drafts on the real layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-past-teams".
 */
export interface PagePastTeam {
  id: number;
  heading: string;
  intro: string;
  /**
   * Browser tab and social-share title for the past teams page (shown as "Q-Summit | …").
   */
  title: string;
  /**
   * Search snippet and WhatsApp/LinkedIn preview text. Also the one-line note for this page in /llms.txt. Aim for 120 to 160 characters.
   */
  metaDescription?: string | null;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Top nav, footer, site title, and /llms.txt identity. Owned by PR. Changes affect every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Brand name in browser tabs and social cards ("Q-Summit | …"). Also the heading of /llms.txt.
   */
  siteTitle: string;
  /**
   * Top navigation links, in display order.
   */
  nav: {
    label: string;
    /**
     * A full URL (https://...), a mailto: address, an internal path (e.g. "/whyq"), or an in-page anchor (e.g. "#why-attend").
     */
    href: string;
    id?: string | null;
  }[];
  footer: {
    /**
     * Fallback for empty page meta descriptions and empty AI summary. Keep factual.
     */
    tagline: string;
    /**
     * Footer link list (Imprint, Privacy Policy, ...).
     */
    links: {
      label: string;
      /**
       * A full URL (https://...), a mailto: address, an internal path (e.g. "/whyq"), or an in-page anchor (e.g. "#why-attend").
       */
      href: string;
      id?: string | null;
    }[];
    socialLinks: {
      label: string;
      href: string;
      /**
       * Stable key used for icon lookup on the site.
       */
      platform: 'tiktok' | 'instagram-qsummit' | 'instagram-qhack' | 'linkedin' | 'youtube';
      id?: string | null;
    }[];
    copyrightHolder: string;
  };
  /**
   * Identity for ChatGPT, Claude, and similar tools. Page link blurbs stay on each page's meta description; /llms-full.txt uses main page sections.
   */
  llms?: {
    /**
     * One or two factual sentences under the /llms.txt title. Encyclopedia tone. Blank → footer tagline.
     */
    summary?: string | null;
    /**
     * One short value line after the summary. Blank → home hero tagline.
     */
    pitch?: string | null;
    /**
     * What / Where / When / Scale / Audience / Value / Contact. One fact per row; no leading dash. Prefer 6 to 10 rows.
     */
    keyFacts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * YYYY-MM-DD when this identity was last checked. Shown near the top of /llms.txt.
     */
    lastReviewed?: string | null;
  };
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Verbatim legal HTML for /imprint, /privacy-policy, and /terms-and-conditions. Never edit without counsel sign-off. Prefer Propose for review so another Admin can check.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  /**
   * Legally reviewed German text. Paste raw HTML exactly as provided by counsel, byte-for-byte; do not reformat, translate, or reword. Shown at /imprint/.
   */
  imprint: string;
  /**
   * Legally reviewed German text. Paste raw HTML exactly as provided by counsel, byte-for-byte; do not reformat, translate, or reword. Shown at /privacy-policy/.
   */
  privacyPolicy: string;
  /**
   * Legally reviewed German text. Paste raw HTML exactly as provided by counsel, byte-for-byte; do not reformat, translate, or reword. Shown at /terms-and-conditions/.
   */
  termsAndConditions: string;
  lastEditedBy?: string | null;
  lastEditedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home_select".
 */
export interface PageHomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
        announcementLines?:
          | T
          | {
              text?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  event?:
    | T
    | {
        startDate?: T;
        endDate?: T;
      };
  stats?:
    | T
    | {
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              value?: T;
              label?: T;
              logos?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  partnerBand?:
    | T
    | {
        items?:
          | T
          | {
              value?: T;
              label?: T;
              logos?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  previousSpeakers?:
    | T
    | {
        heading?: T;
        intro?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  whyAttend?:
    | T
    | {
        heading?: T;
        intro?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  faqSection?:
    | T
    | {
        heading?: T;
        intro?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-whyq_select".
 */
export interface PageWhyqSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  audiences?:
    | T
    | {
        anchorId?: T;
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        imageFile?: T;
        imageAlt?: T;
        imageLeft?: T;
        id?: T;
      };
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-speaker_select".
 */
export interface PageSpeakerSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  panels?:
    | T
    | {
        title?: T;
        description?: T;
        iconKey?: T;
        id?: T;
      };
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-partner_select".
 */
export interface PagePartnerSelect<T extends boolean = true> {
  heading?: T;
  cta?:
    | T
    | {
        heading?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-program_select".
 */
export interface PageProgramSelect<T extends boolean = true> {
  agenda?:
    | T
    | {
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              date?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  closingCta?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-hackathon_select".
 */
export interface PageHackathonSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  partners?:
    | T
    | {
        heading?: T;
        groups?:
          | T
          | {
              group?: T;
              partners?:
                | T
                | {
                    name?: T;
                    href?: T;
                    logoFile?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        heading?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  schedule?:
    | T
    | {
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              date?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  closingCta?:
    | T
    | {
        heading?: T;
        text?: T;
        mailtoLabel?: T;
        mailtoEmail?: T;
      };
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-our-team_select".
 */
export interface PageOurTeamSelect<T extends boolean = true> {
  heading?: T;
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-jobs_select".
 */
export interface PageJobsSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  detailHowToContactHeading?: T;
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-tickets_select".
 */
export interface PageTicketsSelect<T extends boolean = true> {
  tiers?:
    | T
    | {
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              name?: T;
              price?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              note?: T;
              buyLabel?: T;
              buyHref?: T;
              id?: T;
            };
      };
  comparison?:
    | T
    | {
        heading?: T;
        intro?: T;
        tiers?:
          | T
          | {
              name?: T;
              price?: T;
              audience?: T;
              id?: T;
            };
        groups?:
          | T
          | {
              group?: T;
              rows?:
                | T
                | {
                    feature?: T;
                    included?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        academicNote?: T;
      };
  categories?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact_select".
 */
export interface PageContactSelect<T extends boolean = true> {
  board?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        members?:
          | T
          | {
              name?: T;
              role?: T;
              email?: T;
              linkLabel?: T;
              id?: T;
            };
      };
  reachOut?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        items?:
          | T
          | {
              label?: T;
              email?: T;
              details?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-past-teams_select".
 */
export interface PagePastTeamsSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  title?: T;
  metaDescription?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        socialLinks?:
          | T
          | {
              label?: T;
              href?: T;
              platform?: T;
              id?: T;
            };
        copyrightHolder?: T;
      };
  llms?:
    | T
    | {
        summary?: T;
        pitch?: T;
        keyFacts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        lastReviewed?: T;
      };
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  imprint?: T;
  privacyPolicy?: T;
  termsAndConditions?: T;
  lastEditedBy?: T;
  lastEditedAt?: T;
  lastPublishedBy?: T;
  lastPublishedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}